Write documentation for VACF
MDAnalysis/transport-analysis pull request #19
Opened 2023-06-16 21:14 UTC by xhgchen

Resolves #8

Changes made in this Pull Request:
 - Update getting started pages
 - Replace `getting_started.rst` with `getting_started.ipynb`
 - Add necessary dependencies
 - Update API docs TOC
 - Add page for `VelocityAutocorr`

2023-06-17 01:43 UTC, hmacdope requested changes

2023-06-17 01:43 UTC, hmacdope commented on transport_analysis/analysis/velocityautocorr.py
> +efficiently calculate a velocity autocorrelation function (VACF).
Give an example of how to use the class.

2023-06-20 23:28 UTC, hmacdope approved these changes
LGTM

2023-06-20 23:33 UTC, orionarcher approved these changes
LGTM

2023-06-20 23:37 UTC, merged