Create plotting function for VACF
MDAnalysis/transport-analysis pull request #23
Opened 2023-07-10 17:37 UTC by xhgchen

Towards #7 

Changes made in this Pull Request:
 - Add `plot_vacf()` to easily plot VACFs via `Matplotlib`

2023-07-11 01:23 UTC, xhgchen commented
Tests are done, but I am struggling with the type hinting for specific class instances. Any advice @hmacdope @orionarcher?

2023-07-11 02:00 UTC, hmacdope requested changes

2023-07-11 02:00 UTC, hmacdope commented on transport_analysis/velocityautocorr.py
> +def plot_vacf(vacf_obj, start=0, stop=0, step=1):
can do type hint with a string  `vacf_obj: "ObJType..." but see above comment.

2023-07-12 00:15 UTC, hmacdope approved these changes
LGTM!

2023-07-12 02:48 UTC, merged